A_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

blog/urls.py
from django.urls import path
from blog.views import *


app_name = 'blog'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('posts-by-tags/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    # path('', PostListView.as_view(), name='post_list'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:post_slug>/', post_detail, name='post_detail'),
    path('post-share/<int:post_id>/', post_share, name='post_share'),
    path('post-comment/<int:post_id>/', post_comment, name='post_comment'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from taggit.managers import TaggableManager

from user.models import User


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = ('DF', 'Draft')
        PUBLISHED = ('PB', 'Published')

    objects = models.Manager()
    published = PublishedManager()

    tag = TaggableManager()
    author = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='blog_posts')

    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.SlugField(max_length=250, unique=True, verbose_name='Адреса URL')
    body = models.TextField(blank=True, verbose_name='Зміст')

    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публікації')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата змінення')

    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name='Статус посту')

    class Meta:
        db_table = 'posts'
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
                       args=[
                           self.publish.year,
                           self.publish.month,
                           self.publish.day,
                           self.slug
                       ]
                       )


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

    class Meta:
        db_table = 'users'
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

blog/forms.py
from django import forms
from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=150)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from lib2to3.fixes.fix_input import context

from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Count
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect

from taggit.models import Tag

from blog.models import *
from blog.forms import *


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'All posts'
        return context

def post_list(request, tag_slug=None):
    posts_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts_list = posts_list.filter(tag__in=[tag])

    paginator = Paginator(posts_list, 2)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'title': 'Post List',
        'tag': tag,
    }
    return render(request, 'blog/list.html', context=context)


def post_detail(request, year, month, day, post_slug):
    post = get_object_or_404(
        Post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=post_slug,
        status=Post.Status.PUBLISHED
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()

    # Схожі пости
    post_tags_ids = post.tag.values_list('id', flat=True)
    similar_posts = Post.published.filter(tag__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tag')).order_by('-same_tags', '-publish')[:4]


    context = {
        'title': 'Post Detail',
        'post': post,
        'comments': comments,
        'form': form,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog/detail.html', context=context)


def post_share(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )

    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n"\
                      f"{cd['name']}`s comments: {cd['comments']}\n"
            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'title': 'Share post',
        'form': form,
        'sent': sent,
        'post': post,
    }
    return render(request, 'blog/share.html', context=context)


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED,
    )
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'title': 'Коментарії',
        'form': form,
        'comment': comment,
        'post': post,
    }
    return render(request, 'blog/comment.html', context=context)

user/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
{% load blog_tags %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
    <div id="content">
    {% block content %}
    {% endblock content %}
</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>
        {% total_posts as total_posts %}
        This is my blog.
        I`ve wrote {{total_posts}} post{{ total_posts|pluralize }}
    </p>
    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}
    <h3>Most commented posts</h3>
    {% get_most_comments_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
        	<li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

templates/blog/comment.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    {% if comment %}
    	<h2>Your comment successfully added!</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post.</a></p>
    {% else %}
        {% include 'blog/includes/comment-form.html' %}
    {% endif %}
{% endblock content %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
	<h1>{{ post.title }}</h1>
    <p class="date">Publish on {{ post.publish }} by {{ post.author.username }}</p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share post</a>
    </p>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    	<p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        <p>
            Not similar posts yet.
        </p>
    {% endfor %}

    {% with comments.count as total_comment %}
        <h2>{{ total_comment }} comment{{ total_comment|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
    	<div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}
    {% include 'blog/includes/comment-form.html' %}
{% endblock content %}

templates/blog/includes/comment-form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Comment">
</form>

templates/blog/latest-posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
	<h1>Welcome to my Blog.</h1>
    {% if tag %}
    	<h2>Posts tagged by {{ tag.name }}</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        {% if post.tag.count > 0 %}
            Tags:
            {% for tag in post.tag.all %}
            	<a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
            
        {% else %}
            <p class="tags">No tag`s yet</p>
        {% endif %}
        <p class="date">
            Published on {{ post.publish}} by {{ post.author.username }}
        </p>
        {{ post.body|truncatechars_html:50|linebreaks }}
    {% endfor %}
    {% include 'pagination.html' with page=posts %}
{% endblock content %}

templates/blog/share.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if sent %}
        <h1>Email was successfully sent!</h1>
        <p>{{ post.title }} was sent to {{ form.cleaned_data.to }}</p>
    {% else %}
        <h1>Share "{{ post.title }}" post.</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div>
                    {{ field.errors }}
                    {{ field.label }}{{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="Send Email">
        </form>
    {% endif %}
{% endblock content %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %} <!-- если есть предыдущая страница, то показываем её кнопку -->
            <a href="?page={{ page.previous_page_number }}">Previous</a> <!-- возвращает номер предыдущей страницы -->
        {% endif %}
        <span class="current">
           Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %} <!-- если есть следующая страница, то показываем её кнопку -->
            <a href="?page={{ page.next_page_number }}">Next</a> <!-- возвращает номер следующей страницы -->
        {% endif %}
    </span>
</div>